version: "3.9"
services:
  neo4j:
    image: "neo4j:5.12"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - data:/data
    environment:
      - NEO4J_AUTH=none
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

volumes:
  data:


