name: Neo4j Integration Test

on:
  push:
    branches: [ "main", "integration" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run docker compsoe
        run: docker compose --file docker-compose-ci.yaml up  -d
      - name: Run docker compose logs
        run: docker compose --file docker-compose-ci.yaml  logs -f -t
