name: Neo4j Integration Test

on:
  push:
    branches: [ "main", "integration" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run docker compsoe
        run: docker compose --file docker-compose-ci.yaml up --wait --detach

      - name: Print logs
        if: always()
        run: docker compose --file docker-compose-ci.yaml logs
